config/routes.rb
Rails.application.routes.draw do

  get 'page/index'
  root 'page#index'
  get '/actors', to: 'actors#index', as: 'actor'
  get '/films', to: 'films#index', as: 'film'
  resources :actors
  resources :films

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_one :team
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_one :premiere
  has_many :teams
end

app/models/premiere.rb
class Premiere < ApplicationRecord
  belongs_to :film
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :film
  belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:name, :birthplace, :birthdate, :horoscope, :votes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :year)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/premieres_controller.rb
class PremieresController < ApplicationController
  before_action :set_premiere, only: [:show, :edit, :update, :destroy]

  # GET /premieres
  # GET /premieres.json
  def index
    @premieres = Premiere.all
  end

  # GET /premieres/1
  # GET /premieres/1.json
  def show
  end

  # GET /premieres/new
  def new
    @premiere = Premiere.new
  end

  # GET /premieres/1/edit
  def edit
  end

  # POST /premieres
  # POST /premieres.json
  def create
    @premiere = Premiere.new(premiere_params)

    respond_to do |format|
      if @premiere.save
        format.html { redirect_to @premiere, notice: 'Premiere was successfully created.' }
        format.json { render :show, status: :created, location: @premiere }
      else
        format.html { render :new }
        format.json { render json: @premiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /premieres/1
  # PATCH/PUT /premieres/1.json
  def update
    respond_to do |format|
      if @premiere.update(premiere_params)
        format.html { redirect_to @premiere, notice: 'Premiere was successfully updated.' }
        format.json { render :show, status: :ok, location: @premiere }
      else
        format.html { render :edit }
        format.json { render json: @premiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premieres/1
  # DELETE /premieres/1.json
  def destroy
    @premiere.destroy
    respond_to do |format|
      format.html { redirect_to premieres_url, notice: 'Premiere was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premiere
      @premiere = Premiere.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def premiere_params
      params.require(:premiere).permit(:date, :budget)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:role, :sex)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/premieres_helper.rb
module PremieresHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthplace %>
    <%= form.text_field :birthplace %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate,:start_year => 1970, :end_year => 2020  %>
  </div>

  <div class="field">
    <%= form.label :horoscope %>
    <%= form.text_field :horoscope %>
  </div>

  <div class="field">
    <%= form.label :votes %>
    <%= form.text_field :votes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthplace</th>
      <th>Birthdate</th>
      <th>Horoscope</th>
      <th>Votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.birthplace %></td>
        <td><%= actor.birthdate %></td>
        <td><%= actor.horoscope %></td>
        <td><%= actor.votes %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Birthplace:</strong>
  <%= @actor.birthplace %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @actor.birthdate %>
</p>

<p>
  <strong>Horoscope:</strong>
  <%= @actor.horoscope %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @actor.votes %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year,:start_year => 1970, :end_year => 2020  %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.name %></td>
        <td><%= film.year %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @film.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @film.year %>
</p>


<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="main">
  <h1></h1>
</header>
<section class="content">
  <nav class="side_nav">
    <ul>
      <li><a class ="v" href="/">Home</a></li>
      <li class='v'><%= link_to 'Actor', actor_path(@actors)%> </li>
      <li class ="v"><%= link_to 'Film', films_path(@film)%> </li>

    </ul>

  </nav>
  <%= yield %>


</section>

</body>
</html>

app/views/premieres/_form.html.erb
<%= form_with(model: premiere, local: true) do |form| %>
  <% if premiere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(premiere.errors.count, "error") %> prohibited this premiere from being saved:</h2>

      <ul>
        <% premiere.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.text_field :budget %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/premieres/edit.html.erb
<h1>Editing Premiere</h1>

<%= render 'form', premiere: @premiere %>

<%= link_to 'Show', @premiere %> |
<%= link_to 'Back', premieres_path %>

app/views/premieres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Premieres</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @premieres.each do |premiere| %>
      <tr>
        <td><%= premiere.date %></td>
        <td><%= premiere.budget %></td>
        <td><%= link_to 'Show', premiere %></td>
        <td><%= link_to 'Edit', edit_premiere_path(premiere) %></td>
        <td><%= link_to 'Destroy', premiere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Premiere', new_premiere_path %>

app/views/premieres/new.html.erb
<h1>New Premiere</h1>

<%= render 'form', premiere: @premiere %>

<%= link_to 'Back', premieres_path %>

app/views/premieres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @premiere.date %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @premiere.budget %>
</p>

<%= link_to 'Edit', edit_premiere_path(@premiere) %> |
<%= link_to 'Back', premieres_path %>